### ISSUE TITLE
uni-tag.vue 中缺少 type=royal 的样式

### ISSUE THREAD

**Issue by FOXKIAR** [dcloudio/uni-ui#1015]
### 发现 Bug
我最近在学习`uni-app`以及`uni-ui`，在[uni-tag文档 Tag Props](https://zh.uniapp.dcloud.io/component/uniui/uni-tag.html#tag-props)中看到 `type` 可选值 `royal` 为紫色想要试一下

| 属性名 | 类型 | 默认值 | 说明 |
| :--: | :--: | :--: | :--: |
| text | String | - | 标签内容 |
| size | String | normal | 大小尺寸，可选值：normal、small |
| type | String | default | 颜色类型，可选值：default（灰色）、primary（蓝色）、success（绿色）、warning(黄色)、error(红色)、royal(紫色) |
| disabled | Boolean | false | 是否为禁用状态 |
| inverted | Boolean | false | 是否无需背景颜色（空心标签） |
| circle | Boolean | false | 是否为圆角 |

但是当我真正用了发现它并不是紫色而是灰色。
```html
<uni-tag text="test" type="royal"/>
<uni-tag :inverted=true text="test" type="royal"/>
```
![Image](https://github.com/user-attachments/assets/1be50c2a-abf8-4802-a326-5c26bc0e0bcb)
### 添加一些代码
查看源代码后发现，代码中并没有定义有关 `royal` 的样式  
我便自己照着源码格式添加了一个：
```scss
$uni-royal: #726aff !default;
.uni-tag {
    &--royal {
        color: #fff;
        background-color: $uni-royal;
        border-color: $uni-royal;
    }
    &--royal--inverted {
        color: $uni-royal;
        border-color: $uni-royal;
    }
}
.uni-tag-text {
    &--royal {
        color: $uni-royal;
    }
}
```
![Image](https://github.com/user-attachments/assets/0873326d-2cef-4b5e-991d-a2b21826ae5b)
我个人觉得这个颜色看起来还不错

### 最后
我还是刚进入计算机专业没学多久的小萌新，还望大佬们多多指教
