### ISSUE TITLE
能不能给uni-popup的uni-transition 增加 custom-class	

### ISSUE THREAD

**Issue by UphkcRNqmafQWcSSSSSS** [dcloudio/uni-ui#467]
小程序下 type="bottom" 实现圆角只能这样写 导致底部多出10px
```scss
.uni-popup__wrapper.bottom {
  border-radius: 10px 10px 0 0;
  position: relative;
  top: -10px
}
```
