### ISSUE TITLE
如何覆盖小程序样式？

### ISSUE THREAD

**Issue by llk2yq** [dcloudio/uni-ui#485]
`vue3` + `vite`，使用了`sass`，下面的方法对`h5`有效，但是小程序无效。
```css
:deep(.checklist-box) {
    margin-right: 0; // 不生效
}
```

**Comment by llk2yq** [comment]
补充一下：
直接写在全局`.scss`文件内是有效的：
```css
.checklist-box {
    margin-right: 0; // 生效
}
```

但是写在组件的`style`标签内则不生效：
```css
<style lang='scss'>
  // ...其它css
  .checklist-box {
      margin-right: 0; // 不生效
  }
  :deep(.checklist-box) {
    margin-right: 0; // 这样写也不生效
  }
</style>
```
