### ISSUE TITLE
uni-forms-item无校验error时，页面间隔较大

### ISSUE THREAD

**Issue by AbelWangYaBo** [dcloudio/uni-ui#538]
目前的uni-forms-item无论是否有校验信息，都会有padding-bottom: 22px，导致表单间隔较大，是否可以考虑只在有校验/报错信息时，才将padding-bottom设置为22px？

页面：uni-forms-item
``` scss

// uni-forms-item

// line 453，注释padding
.m-forms-item__inner {
  // padding-bottom: 22px;
}

// line 544
// 当有error时，增加padding-bottom
.m-forms-item-error {
  .m-forms-item__inner {
    padding-bottom: 22px;
  }
}
```
